name: install-uv

on: 
  workflow_dispatch:
  

jobs:
  train:
    env:
      # (or) make sure readS3FullAccess ROLE attached to Runner
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest

    steps:
      # checkout our code
      - uses: actions/checkout@v4

      # install aws-cli
      - name: install aws-cli
        run: |
          sudo apt install curl unzip -y
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      #  module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'
      - name: fix issue
        run: |
          python3 -m pip install pip --upgrade
          pip install pyopenssl --upgrade

      # install uv
      - name: "install-uv & cache-it"
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
    
      - name: "setting up python3"
        uses: actions/setup-python@v5
        # with:
        #   python-version-file: ".python-version"

      - name: "install dependencies ğŸ“"
        run: uv sync --group visuals --group prod --extra cpu   # --env-file .env

      - name: "download s3ğŸª£"
        run: echo "download dataset"

      - name: "hparamsğŸ’ğŸ¦§ model"
        run: echo "download dataset"
      
      - name: "trainğŸ‹ï¸ model"
        run: echo "download dataset"

      - name: "push to S3ğŸª£ ğŸŒ€"
        run: echo "download dataset"

      - name: "test model â›“ï¸"
        run: echo "download dataset"
      
      - name: "inference model ğŸš€"
        run: echo "download dataset"
      

      # Make Sure you created a SPACE first
      - name: "Logging to HFSpaceğŸ§‘â€ğŸš€ "
        run: python -c 'import huggingface_hub; huggingface_hub.login(token="${{ secrets.hf_token }}")'


      - name: "print BEST hparams"
        run: echo "done and dusted!!ğŸ‰"

      